#!/usr/bin/env python3
"""Generate high-quality Cantonese MP3s for every phrase in data/lessons.js.

For each unique `hanzi` phrase, synthesize audio/<key>.mp3 with edge-tts
(voice zh-HK-HiuMaanNeural) and write audio/manifest.js mapping phrase -> key.
Existing, non-empty MP3s are skipped, so re-runs are fast and diffs small.

Generation needs open internet to Microsoft's TTS host, so it cannot run in
restricted sandboxes — use GitHub Actions or a local machine. --dry-run lists
the phrases with no network and no writes.

Usage:
    python3 scripts/generate_audio.py            # synthesize missing audio
    python3 scripts/generate_audio.py --dry-run  # list phrases, write nothing
"""
import asyncio
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from extract_phrases import extract_phrases, phrase_key

ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, "data", "lessons.js")
AUDIO_DIR = os.path.join(ROOT, "audio")
MANIFEST = os.path.join(AUDIO_DIR, "manifest.js")
VOICE = "zh-HK-HiuMaanNeural"
RETRIES = 3


def load_phrases():
    with open(DATA, encoding="utf-8") as f:
        return extract_phrases(f.read())


def mp3_path(key):
    return os.path.join(AUDIO_DIR, key + ".mp3")


def has_audio(key):
    p = mp3_path(key)
    return os.path.exists(p) and os.path.getsize(p) > 0


async def synth(text, key):
    """Synthesize one phrase. Return True on success (non-empty file)."""
    import edge_tts
    path = mp3_path(key)
    for attempt in range(1, RETRIES + 1):
        try:
            await edge_tts.Communicate(text, VOICE).save(path)
            if os.path.exists(path) and os.path.getsize(path) > 0:
                return True
            raise RuntimeError("empty file written")
        except Exception as e:  # report, clean up, retry
            print("  attempt %d/%d failed for %r: %s" % (attempt, RETRIES, text, e))
            if os.path.exists(path) and os.path.getsize(path) == 0:
                os.remove(path)
            if attempt < RETRIES:
                await asyncio.sleep(attempt)
    return False


def write_manifest(mapping):
    body = json.dumps(mapping, ensure_ascii=False, indent=2, sort_keys=True)
    with open(MANIFEST, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by scripts/generate_audio.py - do not edit. */\n")
        f.write("window.AUDIO_MANIFEST = " + body + ";\n")


async def run(dry_run):
    phrases = load_phrases()
    print("Found %d unique phrases in data/lessons.js" % len(phrases))

    if dry_run:
        for p in phrases[:5]:
            print("  -", p, "->", phrase_key(p) + ".mp3")
        print("(dry run: no audio generated, no files written)")
        return 0

    os.makedirs(AUDIO_DIR, exist_ok=True)
    mapping = {}
    generated = skipped = failed = 0
    for text in phrases:
        key = phrase_key(text)
        if has_audio(key):
            mapping[text] = key
            skipped += 1
            continue
        print("Generating:", text)
        if await synth(text, key):
            mapping[text] = key
            generated += 1
        else:
            failed += 1

    write_manifest(mapping)

    missing = [t for t, k in mapping.items() if not has_audio(k)]
    print("\nSummary: %d generated, %d already present, %d failed, %d in manifest"
          % (generated, skipped, failed, len(mapping)))
    if missing:
        print("ERROR: manifest references %d missing files" % len(missing))
        return 1
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(asyncio.run(run("--dry-run" in sys.argv[1:])))
